* mithril-starter-rollup

** TODO 
- server dashboard
- rss reader (for blog)
- convert to browser extension
    - Ctrl-c-p (projectile) => show project dashboard

** Setup

Install dependencies

#+BEGIN_SRC sh 
npm install
#+END_SRC


** Build and watch

Script commands defined in `package.json`:

- `build`: creates a minified bundle in `dist/js/`
- `serve`: serves the build directory at [localhost:5000](http://localhost:5000/)
- `dev`: starts a local webserver; creates a bundle in `dist/js/` that is being updated with each code change; calls LiveReload to refresh the browser after code changes are built

Call `npm run dev` and open a web page at [localhost:3000](http://localhost:3000/). The port number is set by environment variable `PORT` in `package.json`.

When making changes, the terminal will show lint errors, if any.

** Configuration files

`scripts` contains a couple of Rollup configuration files. The scripts use `rollup.base.js` as base configuration.

FYI, the base configuration:

- Exports `createConfig({ includeDepencies })`
- Reads `package.json` to read package dependencies. If `includeDepencies` is `true`, it will include those dependencies in the build file
- Creates global package names; and sets global `m` for package "mithril".

*** Bundler configuration

- `rollup.es.js`: Builds an ES2015 module with syntax features that node supports
- `rollup.umd.js`: Builds a UMD bundle
- `rollup.watch.js`: Builds a UMD bundle that is updated with each file change

Optional environment variables:

- `DEPS` (Number 0 or 1): include dependencies
- `WATCH_DIR` (String): sets the watch directory when running the `dev` script
- `PORT` (Number): sets the http server port when running the `dev` script

Other configuration file:

- `.babelrc`: Babel configuration

** License

MIT
